### ISSUE TITLE
【请求】能否提供贵字幕组对应api接口？

### ISSUE THREAD

**Issue by CarefulDeveloper** [david082321/FurrySub#1]
本人想要使用贵字幕组的字幕来观看泰区番剧。个人比较使用电脑端的视频工具观看，所以无法使用漫游工具，也就不能使用贵司字幕。本人能够保证不滥用接口。如若其中存在一些不妥之处致使贵字幕组不能提供接口，本人也能够理解。期待贵字幕组的回复，谢谢！

**Comment by JasonKhew96** [comment]
咱不是字幕组，大部分字幕是搬运港澳台的，自己手搓

**Comment by CarefulDeveloper** [comment]
嗯，我也了解到贵字幕组是属于搬运的那种。但我还是想问下贵搬运字幕组搬运的字幕可以通过Api访问吗？我其实也知道很多番剧港澳台有字幕，但是对于泰区有的，港澳台没有的番剧就比较难受了。所以我也是在这一部分的字幕。

**Comment by JasonKhew96** [comment]
F12 直接找，又不加密
